import Link from "next/link"

export default function HomePage() {
  return (
    <main className="min-h-screen bg-gray-50">
      <div className="mx-auto flex min-h-screen max-w-6xl flex-col items-center justify-center px-6 text-center">
        <span className="rounded-full border border-blue-200 bg-blue-50 px-4 py-1 text-sm font-medium text-blue-700">
          Sharia-Compliant Algorithmic Trading
        </span>

        <h1 className="mt-6 max-w-4xl text-5xl font-bold tracking-tight text-gray-900">
          Build, test and automate halal trading strategies.
        </h1>

        <p className="mt-6 max-w-2xl text-lg text-gray-600">
          Backtest investment strategies, monitor real-time market signals,
          verify compliance and connect your broker — all in one platform.
        </p>

        <div className="mt-10 flex flex-wrap justify-center gap-4">
          <Link href="/pricing" className="btn-primary">
            Get Started
          </Link>

          <Link
            href="/login"
            className="rounded-lg border border-gray-300 bg-white px-5 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-100"
          >
            Sign In
          </Link>
        </div>

        <div className="mt-16 grid w-full max-w-4xl grid-cols-1 gap-4 md:grid-cols-3">
          <div className="card text-center">
            <h3 className="font-semibold">Backtesting</h3>
            <p className="mt-2 text-sm text-gray-500">
              Test strategies against historical market data before investing.
            </p>
          </div>

          <div className="card text-center">
            <h3 className="font-semibold">Live Signals</h3>
            <p className="mt-2 text-sm text-gray-500">
              Receive trading signals generated by active strategies.
            </p>
          </div>

          <div className="card text-center">
            <h3 className="font-semibold">Halal Compliance</h3>
            <p className="mt-2 text-sm text-gray-500">
              Verify investments using built-in Sharia compliance checks.
            </p>
          </div>
        </div>
      </div>
    </main>
  )
}
